# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# === Builder Stage ===
FROM node:lts-alpine AS builder

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json tsconfig.json ./
RUN npm install

# Copy source and build
COPY src ./src
RUN npm run build

# === Production Stage ===
FROM node:lts-alpine AS runner

WORKDIR /app

# Install only production dependencies
COPY package.json package-lock.json ./
RUN npm install --production

# Copy built output
COPY --from=builder /app/build ./build

# Use unprivileged user (optional)
# RUN addgroup -S app && adduser -S app -G app
# USER app

ENTRYPOINT ["node", "build/index.js"]
